name: production_deployment

on:
  push:
    tags:
      - v**-production

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_VARIABLES }}" > .env
          
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_NAMESPACE }}/miming-website:latest .

      - name: Push image to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push ${{ secrets.DOCKER_HUB_NAMESPACE }}/miming-website:latest
          
      - name: SSH to EC2 Server
        run: |
          mkdir ~/.ssh
          echo -e "${{ secrets.PRODUCTION_PRIVATE_KEY }}" > ~/.ssh/ssh-key
          chmod 400 ~/.ssh/ssh-key
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ssh-key ${{ secrets.PRODUCTION_USERNAME }}@${{ secrets.PRODUCTION_HOST }} \
            'cd ${{ secrets.PRODUCTION_PATH }} && \
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} && \
            sh deploy_production.sh'